{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synchronizer.fullname" . }}-secret
  labels:
    {{- include "synchronizer.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-username: {{ .Values.database.username | quote }}
  database-password: {{ .Values.database.password | quote }}
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
